# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='website_header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='About Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='website_header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Careers Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'Careers Page',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='website_header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Contact Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='website_header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Gallery Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'Gallery Page',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Home Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'Home Page',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Photo title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Short description')),
                ('picture', models.ImageField(upload_to='home_photos')),
                ('page', models.ForeignKey(blank=True, help_text='Select Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_photos', to='website.HomePage')),
            ],
            options={
                'verbose_name_plural': 'Home Website Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='website_header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Projects Page', max_length=255, verbose_name='Page title')),
            ],
            options={
                'verbose_name_plural': 'Projects Page',
            },
        ),
    ]
