# Generated by Django 2.2.22 on 2021-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homelogoheader_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='map_address',
            field=models.CharField(blank=True, default='MillworkPioneers Address', max_length=255, verbose_name='Map Address'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_latitude',
            field=models.CharField(blank=True, default='33.8080843', help_text='Use google url coordinates', max_length=50, verbose_name='Latitude Coordinates'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_longitude',
            field=models.CharField(blank=True, default='-118.0604532', help_text='Use google url coordinates', max_length=50, verbose_name='Longitude Coordinates'),
        ),
    ]
