# Generated by Django 2.2.22 on 2021-05-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210510_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='main_video',
            field=models.URLField(blank=True, default='https://youtu.be/CZb9XTONNkA', help_text='Copy from youtube page', verbose_name='Youtube URL'),
        ),
    ]
