# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woodworkpage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Woodwork Pioneers Page'},
        ),
        migrations.AddField(
            model_name='woodworkpage',
            name='main_video',
            field=models.URLField(blank=True, verbose_name='Youtube or vimeo URL'),
        ),
    ]
