# Generated by Django 2.2.22 on 2021-05-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodwork', '0002_auto_20190113_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodworkpage',
            name='main_video',
            field=models.URLField(blank=True, default='https://youtu.be/CZb9XTONNkA', help_text='Copy from youtube page', verbose_name='Youtube URL'),
        ),
    ]
