# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 03:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Client name')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Website url')),
                ('headline', models.CharField(blank=True, default='', max_length=255, verbose_name='Company headline')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, default='', max_length=255, verbose_name='Fax')),
                ('headline', models.CharField(blank=True, default='', max_length=255, verbose_name='Headline')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Address')),
                ('facebook', models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, default='', max_length=255, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, default='', max_length=255, verbose_name='Linkedin')),
                ('service_area', models.TextField(blank=True, default='', verbose_name='Service area')),
                ('hours_operation', models.TextField(blank=True, default='', verbose_name='Hours of operation')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Metadata')),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
                'ordering': ['created_at'],
            },
        ),
    ]
