# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 03:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bid_due',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Estimated start date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='prevailing_wage',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=255, verbose_name='Prevailing wage'),
        ),
    ]
