# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180912_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, upload_to='alliances_logos'),
        ),
    ]
