# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_video',
            field=models.URLField(blank=True, verbose_name='Youtube or vimeo URL'),
        ),
    ]
