# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_main_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Youtube'),
        ),
    ]
