# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181007_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gmaps',
            field=models.URLField(blank=True, verbose_name='Google Maps Link'),
        ),
    ]
