# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Reviewer name')),
                ('description', models.TextField(blank=True, default='')),
                ('place', models.CharField(blank=True, default='', max_length=255, verbose_name='Place name')),
                ('avatar', models.ImageField(upload_to='avatars')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
