# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180909_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title of project')),
                ('description', models.TextField(blank=True, default='')),
                ('client', models.CharField(blank=True, default='', max_length=255, verbose_name='Client name')),
                ('status_project', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('IN PROGRESS', 'In progress')], default='COMPLETED', help_text='Select one', max_length=255, verbose_name='Status of the project')),
                ('main_picture', models.ImageField(blank=True, upload_to='projects', verbose_name='Main picture for project')),
                ('is_display_on_website', models.BooleanField(default=True, help_text='Select "Yes" to display on site', verbose_name='Will display on site?')),
            ],
            options={
                'verbose_name_plural': 'Millwork Projects',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Select one project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='gallery.Project'),
        ),
    ]
