# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180913_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='')),
                ('main_picture', models.ImageField(blank=True, upload_to='services', verbose_name='Main picture for project')),
            ],
            options={
                'verbose_name_plural': 'Millwork Services',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Gallery Photos'},
        ),
    ]
