# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180916_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Url slug'),
        ),
    ]
