# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='This field is auto-generated', max_length=255, verbose_name='Url slug'),
        ),
    ]
