# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180919_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Gallery Photos'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Millwork Projects'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Reviews(★★★★★)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Millwork Services'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Photo Tags'},
        ),
    ]
