# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20181007_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_display_on_website',
            field=models.BooleanField(default=True, help_text='Select "Yes" to display on site', verbose_name='Will display on site?'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='This field is auto-generated', max_length=255, verbose_name='Url slug'),
        ),
    ]
