# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_project_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brand',
            field=models.CharField(choices=[('MILLWORK', 'Millwork Pioneers'), ('WOODWORK', 'Woodwork Pioneers')], default='MILLWORK', help_text='Select the correct!', max_length=100, verbose_name='Company brand'),
        ),
    ]
